# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
