# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 13:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('price', models.FloatField(blank=True, null=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Invader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_reference', models.CharField(default=events.models.create_payment_reference, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_from', models.GenericIPAddressField(blank=True, null=True)),
                ('payment_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('activities', models.ManyToManyField(blank=True, to='events.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Invasion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(blank=True, null=True)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='invader',
            name='invasion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Invasion'),
        ),
        migrations.AddField(
            model_name='invader',
            name='surfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='invasion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Invasion'),
        ),
    ]
