# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='person_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
