# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 07:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_reference', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_from', models.GenericIPAddressField(null=True)),
                ('payment_confirmed_at', models.DateTimeField(blank=True)),
                ('activities', models.ManyToManyField(blank=True, to='activities.Activity')),
                ('invasion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Invasion')),
                ('surfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='invasion',
            name='surfers',
            field=models.ManyToManyField(through='events.Invader', to=settings.AUTH_USER_MODEL),
        ),
    ]
