# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170515_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invader',
            name='activities',
            field=models.ManyToManyField(blank=True, null=True, to='activities.Activity'),
        ),
        migrations.AlterField(
            model_name='invader',
            name='created_from',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invader',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
