# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170515_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invasion',
            name='surfers',
        ),
        migrations.AlterField(
            model_name='invader',
            name='activities',
            field=models.ManyToManyField(blank=True, to='activities.Activity'),
        ),
    ]
