# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 07:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20170515_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='invasion',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
