# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfer',
            name='bw_link',
            field=models.URLField(blank=True, verbose_name='BeWelcome profile link'),
        ),
        migrations.AlterField(
            model_name='surfer',
            name='cs_link',
            field=models.URLField(blank=True, verbose_name='CouchSurfing profile link'),
        ),
        migrations.AlterField(
            model_name='surfer',
            name='facebook_link',
            field=models.URLField(blank=True, verbose_name='Facebook profile link'),
        ),
    ]
